name: botica_mobile_flutter
description: Aplicacion movil Flutter para consumir la API REST de EconoSalud.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/econo_salud_logo.png
    - assets/images/econo_salud_symbol.jpg
